# Generated by Django 3.2.6 on 2021-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductAmount', models.IntegerField()),
            ],
        ),
    ]
